now

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -23,10 +23,12 @@ jobs:
         run: |
           eval $(ssh-agent -s)
           echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa_work_to_home
-
+          echo "from github" hi_github
       - name: Add remote host to known hosts
         run: |
-          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
+          echo "Checking host: ${{ secrets.REMOTE_HOST }}"
+          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} || echo "ssh-keyscan failed"
+
 
       - name: Deploy to remote server
         run: |
